"""add user_id to students

Revision ID: d0eaafcca5ac
Revises: 944f0a46ee85
Create Date: 2026-07-23 00:36:58.791822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0eaafcca5ac'
down_revision: Union[str, None] = '944f0a46ee85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'students', ['user_id'])
    op.create_foreign_key(None, 'students', 'users', ['user_id'], ['id'])
    op.drop_constraint('teachers_employee_id_key', 'teachers', type_='unique')
    op.drop_column('teachers', 'employee_id')
    op.drop_column('teachers', 'department')
    op.drop_column('teachers', 'designation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('designation', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('teachers', sa.Column('department', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('teachers', sa.Column('employee_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('teachers_employee_id_key', 'teachers', ['employee_id'])
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_constraint(None, 'students', type_='unique')
    op.drop_column('students', 'user_id')
    # ### end Alembic commands ###
