from dataclasses import dataclass


@dataclass
class VoiceMessage:
    """
    Represents a speech message generated by the Voice Engine.
    """

    message: str

    priority: str = "normal"

    interrupt: bool = False

    source: str = "system"