from enum import Enum


class AuditAction(str, Enum):
    LOGIN = "LOGIN"
    LOGOUT = "LOGOUT"
    REGISTER = "REGISTER"

    ATTENDANCE_MARKED = "ATTENDANCE_MARKED"

    VOICE_COMMAND = "VOICE_COMMAND"

    CALL_TEACHER = "CALL_TEACHER"

    OCR_UPLOAD = "OCR_UPLOAD"

    LECTURE_CREATED = "LECTURE_CREATED"

    DEVICE_CONTROL = "DEVICE_CONTROL"

    ACCESSIBILITY_UPDATED = "ACCESSIBILITY_UPDATED"

    USER_CREATED = "USER_CREATED"

    USER_UPDATED = "USER_UPDATED"

    USER_DELETED = "USER_DELETED"

    CLASSROOM_CREATED = "CLASSROOM_CREATED"

    CLASSROOM_UPDATED = "CLASSROOM_UPDATED"
    
    CLASSROOM_DELETED = "CLASSROOM_DELETED"