USE_GPU = True

LANGUAGE = "en"

USE_ANGLE_CLASSIFIER = True

SHOW_LOG = False

MIN_TEXT_SCORE = 0.60

OCR_REGION_TOP = 0.05
OCR_REGION_BOTTOM = 0.50

OCR_REGION_LEFT = 0.10
OCR_REGION_RIGHT = 0.90

# OCR Configuration

MIN_TEXT_SCORE = 0.60

OCR_REGION_TOP = 0.05
OCR_REGION_BOTTOM = 0.50

OCR_REGION_LEFT = 0.10
OCR_REGION_RIGHT = 0.90

MAX_TEXT_LENGTH = 5000

MIN_TEXT_LENGTH = 3

SAVE_OCR_IMAGES = False

# ==========================================
# AI Pipeline Configuration
# ==========================================

ENABLE_OCR = True

ENABLE_OBJECT_DETECTION = True

ENABLE_ACCESSIBILITY = True

ENABLE_AI_NOTES = True

ENABLE_ANALYTICS = True

ENABLE_NOTIFICATIONS = True

ENABLE_PERFORMANCE_LOGS = True

SAVE_DEBUG_IMAGES = False

MAX_DETECTIONS = 100

PIPELINE_TIMEOUT_MS = 5000

# OCR

OCR_CHANGE_THRESHOLD = 0.90

OCR_MIN_TEXT_LENGTH = 5