export interface SupportedLanguage {
  code: string;
  name: string;
  nativeName: string;
  region?: string;
}

export const SUPPORTED_LANGUAGES: SupportedLanguage[] = [
  // ─── Primary Indian Regional & Official Languages (All 22 Scheduled + Major Dialects) ───
  { code: 'en', name: 'English', nativeName: 'English (US)', region: 'Global / India' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', region: 'India (Andhra / Telangana)' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', region: 'India' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', region: 'India (Tamil Nadu) / Sri Lanka' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', region: 'India (Karnataka)' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', region: 'India (Kerala)' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', region: 'India (Maharashtra)' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', region: 'India (West Bengal) / Bangladesh' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', region: 'India (Gujarat)' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', region: 'India (Punjab)' },
  { code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ', region: 'India (Odisha)' },
  { code: 'as', name: 'Assamese', nativeName: 'অসমীয়া', region: 'India (Assam)' },
  { code: 'ur', name: 'Urdu', nativeName: 'اردو', region: 'India / South Asia' },
  { code: 'sa', name: 'Sanskrit', nativeName: 'संस्कृतम्', region: 'India (Classical)' },
  { code: 'ne', name: 'Nepali', nativeName: 'नेपाली', region: 'India / Nepal' },
  { code: 'sd', name: 'Sindhi', nativeName: 'سنڌي / सिन्धी', region: 'India / Pakistan' },
  { code: 'mai', name: 'Maithili', nativeName: 'मैथिली', region: 'India (Bihar / Jharkhand)' },
  { code: 'doi', name: 'Dogri', nativeName: 'डोगरी', region: 'India (Jammu & Kashmir)' },
  { code: 'kok', name: 'Konkani', nativeName: 'कोंकणी', region: 'India (Goa / Maharashtra)' },
  { code: 'mni-Mtei', name: 'Manipuri (Meitei)', nativeName: 'ꯃꯤꯇꯩꯂꯣꯟ', region: 'India (Manipur)' },
  { code: 'brx', name: 'Bodo', nativeName: 'बड़ो', region: 'India (Assam)' },
  { code: 'sat', name: 'Santali', nativeName: 'ᱥᱟᱱᱛᱟᱲᱤ', region: 'India (Jharkhand / Odisha)' },
  { code: 'ks', name: 'Kashmiri', nativeName: 'کٲشُر / कश्मीरी', region: 'India (Kashmir)' },
  { code: 'bho', name: 'Bhojpuri', nativeName: 'भोजपुरी', region: 'India (UP / Bihar)' },
  { code: 'awa', name: 'Awadhi', nativeName: 'अवधी', region: 'India (UP)' },
  { code: 'mag', name: 'Magahi', nativeName: 'मगही', region: 'India (Bihar)' },

  // ─── Major Asian & East Asian Languages ───
  { code: 'ja', name: 'Japanese', nativeName: '日本語', region: 'Japan' },
  { code: 'ko', name: 'Korean', nativeName: '한국어', region: 'South Korea' },
  { code: 'zh-CN', name: 'Chinese (Simplified)', nativeName: '简体中文', region: 'China / Singapore' },
  { code: 'zh-TW', name: 'Chinese (Traditional)', nativeName: '繁體中文', region: 'Taiwan / Hong Kong' },
  { code: 'vi', name: 'Vietnamese', nativeName: 'Tiếng Việt', region: 'Vietnam' },
  { code: 'th', name: 'Thai', nativeName: 'ไทย', region: 'Thailand' },
  { code: 'id', name: 'Indonesian', nativeName: 'Bahasa Indonesia', region: 'Indonesia' },
  { code: 'ms', name: 'Malay', nativeName: 'Bahasa Melayu', region: 'Malaysia / Brunei' },
  { code: 'tl', name: 'Filipino (Tagalog)', nativeName: 'Wikang Filipino', region: 'Philippines' },
  { code: 'my', name: 'Burmese', nativeName: 'မြန်မာစာ', region: 'Myanmar' },
  { code: 'km', name: 'Khmer', nativeName: 'ភាសាខ្មែរ', region: 'Cambodia' },
  { code: 'lo', name: 'Lao', nativeName: 'ພາສາລາວ', region: 'Laos' },
  { code: 'si', name: 'Sinhala', nativeName: 'සිංහල', region: 'Sri Lanka' },
  { code: 'mn', name: 'Mongolian', nativeName: 'Монгол хэл', region: 'Mongolia' },
  { code: 'bo', name: 'Tibetan', nativeName: 'བོད་སྐད་', region: 'Tibet' },
  { code: 'dz', name: 'Dzongkha', nativeName: 'རྫོང་ཁ', region: 'Bhutan' },
  { code: 'jv', name: 'Javanese', nativeName: 'Basa Jawa', region: 'Indonesia' },
  { code: 'su', name: 'Sundanese', nativeName: 'Basa Sunda', region: 'Indonesia' },
  { code: 'ceb', name: 'Cebuano', nativeName: 'Sinugboanon', region: 'Philippines' },
  { code: 'ilo', name: 'Ilocano', nativeName: 'Ilokano', region: 'Philippines' },

  // ─── Major European Languages ───
  { code: 'es', name: 'Spanish', nativeName: 'Español', region: 'Spain / Latin America' },
  { code: 'fr', name: 'French', nativeName: 'Français', region: 'France / Canada / Africa' },
  { code: 'de', name: 'German', nativeName: 'Deutsch', region: 'Germany / Austria / Switzerland' },
  { code: 'it', name: 'Italian', nativeName: 'Italiano', region: 'Italy / Switzerland' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português', region: 'Portugal / Brazil' },
  { code: 'ru', name: 'Russian', nativeName: 'Русский', region: 'Russia / Eastern Europe' },
  { code: 'uk', name: 'Ukrainian', nativeName: 'Українська', region: 'Ukraine' },
  { code: 'pl', name: 'Polish', nativeName: 'Polski', region: 'Poland' },
  { code: 'nl', name: 'Dutch', nativeName: 'Nederlands', region: 'Netherlands / Belgium' },
  { code: 'sv', name: 'Swedish', nativeName: 'Svenska', region: 'Sweden' },
  { code: 'no', name: 'Norwegian', nativeName: 'Norsk', region: 'Norway' },
  { code: 'da', name: 'Danish', nativeName: 'Dansk', region: 'Denmark' },
  { code: 'fi', name: 'Finnish', nativeName: 'Suomi', region: 'Finland' },
  { code: 'el', name: 'Greek', nativeName: 'Ελληνικά', region: 'Greece / Cyprus' },
  { code: 'cs', name: 'Czech', nativeName: 'Čeština', region: 'Czech Republic' },
  { code: 'ro', name: 'Romanian', nativeName: 'Română', region: 'Romania / Moldova' },
  { code: 'hu', name: 'Hungarian', nativeName: 'Magyar', region: 'Hungary' },
  { code: 'bg', name: 'Bulgarian', nativeName: 'Български', region: 'Bulgaria' },
  { code: 'sr', name: 'Serbian', nativeName: 'Српски', region: 'Serbia / Balkans' },
  { code: 'hr', name: 'Croatian', nativeName: 'Hrvatski', region: 'Croatia' },
  { code: 'sk', name: 'Slovak', nativeName: 'Slovenčina', region: 'Slovakia' },
  { code: 'sl', name: 'Slovenian', nativeName: 'Slovenščina', region: 'Slovenia' },
  { code: 'lt', name: 'Lithuanian', nativeName: 'Lietuvių', region: 'Lithuania' },
  { code: 'lv', name: 'Latvian', nativeName: 'Latviešu', region: 'Latvia' },
  { code: 'et', name: 'Estonian', nativeName: 'Eesti', region: 'Estonia' },
  { code: 'is', name: 'Icelandic', nativeName: 'Íslenska', region: 'Iceland' },
  { code: 'ga', name: 'Irish', nativeName: 'Gaeilge', region: 'Ireland' },
  { code: 'cy', name: 'Welsh', nativeName: 'Cymraeg', region: 'Wales' },
  { code: 'gd', name: 'Scottish Gaelic', nativeName: 'Gàidhlig', region: 'Scotland' },
  { code: 'eu', name: 'Basque', nativeName: 'Euskara', region: 'Spain / France' },
  { code: 'ca', name: 'Catalan', nativeName: 'Català', region: 'Catalonia / Spain' },
  { code: 'gl', name: 'Galician', nativeName: 'Galego', region: 'Galicia / Spain' },
  { code: 'mt', name: 'Maltese', nativeName: 'Malti', region: 'Malta' },
  { code: 'lb', name: 'Luxembourgish', nativeName: 'Lëtzebuergesch', region: 'Luxembourg' },
  { code: 'bs', name: 'Bosnian', nativeName: 'Bosanski', region: 'Bosnia' },
  { code: 'mk', name: 'Macedonian', nativeName: 'Македонски', region: 'North Macedonia' },
  { code: 'sq', name: 'Albanian', nativeName: 'Shqip', region: 'Albania / Kosovo' },
  { code: 'be', name: 'Belarusian', nativeName: 'Беларуская', region: 'Belarus' },
  { code: 'la', name: 'Latin', nativeName: 'Lingua Latina', region: 'Classical / Vatican' },
  { code: 'eo', name: 'Esperanto', nativeName: 'Esperanto', region: 'International' },
  { code: 'yi', name: 'Yiddish', nativeName: 'ייִדיש', region: 'Global Jewish' },

  // ─── Middle Eastern & Central Asian Languages ───
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', region: 'Middle East / North Africa' },
  { code: 'fa', name: 'Persian (Farsi)', nativeName: 'فارسی', region: 'Iran / Afghanistan' },
  { code: 'he', name: 'Hebrew', nativeName: 'עברית', region: 'Israel' },
  { code: 'tr', name: 'Turkish', nativeName: 'Türkçe', region: 'Turkey / Cyprus' },
  { code: 'ku', name: 'Kurdish (Kurmanji)', nativeName: 'Kurdî', region: 'Kurdistan / Middle East' },
  { code: 'ckb', name: 'Kurdish (Sorani)', nativeName: 'سۆرانی', region: 'Iraq / Iran' },
  { code: 'ps', name: 'Pashto', nativeName: 'پښتو', region: 'Afghanistan / Pakistan' },
  { code: 'hy', name: 'Armenian', nativeName: 'Հայերեն', region: 'Armenia' },
  { code: 'az', name: 'Azerbaijani', nativeName: 'Azərbaycan dili', region: 'Azerbaijan' },
  { code: 'ka', name: 'Georgian', nativeName: 'ქართული', region: 'Georgia' },
  { code: 'kk', name: 'Kazakh', nativeName: 'Қазақ тілі', region: 'Kazakhstan' },
  { code: 'uz', name: 'Uzbek', nativeName: 'Oʻzbekcha', region: 'Uzbekistan' },
  { code: 'ky', name: 'Kyrgyz', nativeName: 'Кыргызча', region: 'Kyrgyzstan' },
  { code: 'tg', name: 'Tajik', nativeName: 'Тоҷикӣ', region: 'Tajikistan' },
  { code: 'tk', name: 'Turkmen', nativeName: 'Türkmençe', region: 'Turkmenistan' },
  { code: 'tt', name: 'Tatar', nativeName: 'Татарча', region: 'Russia (Tatarstan)' },
  { code: 'ug', name: 'Uyghur', nativeName: 'ئۇيغۇرچە', region: 'Central Asia' },

  // ─── African Languages ───
  { code: 'sw', name: 'Swahili', nativeName: 'Kiswahili', region: 'East Africa (Kenya, Tanzania)' },
  { code: 'am', name: 'Amharic', nativeName: 'አማርኛ', region: 'Ethiopia' },
  { code: 'ha', name: 'Hausa', nativeName: 'Harshen Hausa', region: 'Nigeria / West Africa' },
  { code: 'yo', name: 'Yoruba', nativeName: 'Èdè Yorùbá', region: 'Nigeria / Benin' },
  { code: 'ig', name: 'Igbo', nativeName: 'Asụsụ Igbo', region: 'Nigeria' },
  { code: 'zu', name: 'Zulu', nativeName: 'isiZulu', region: 'South Africa' },
  { code: 'xh', name: 'Xhosa', nativeName: 'isiXhosa', region: 'South Africa' },
  { code: 'af', name: 'Afrikaans', nativeName: 'Afrikaans', region: 'South Africa / Namibia' },
  { code: 'so', name: 'Somali', nativeName: 'Af-Soomaali', region: 'Somalia / Horn of Africa' },
  { code: 'om', name: 'Oromo', nativeName: 'Afaan Oromoo', region: 'Ethiopia / Kenya' },
  { code: 'ti', name: 'Tigrinya', nativeName: 'ትግርኛ', region: 'Eritrea / Ethiopia' },
  { code: 'rw', name: 'Kinyarwanda', nativeName: 'Ikinyarwanda', region: 'Rwanda' },
  { code: 'sn', name: 'Shona', nativeName: 'chiShona', region: 'Zimbabwe' },
  { code: 'st', name: 'Sesotho', nativeName: 'Sesotho', region: 'Lesotho / South Africa' },
  { code: 'ny', name: 'Chichewa', nativeName: 'Chichewa', region: 'Malawi / Zambia' },
  { code: 'mg', name: 'Malagasy', nativeName: 'Fiteny Malagasy', region: 'Madagascar' },
  { code: 'ln', name: 'Lingala', nativeName: 'Lingála', region: 'DR Congo / Congo' },
  { code: 'lg', name: 'Luganda', nativeName: 'Oluganda', region: 'Uganda' },
  { code: 'ak', name: 'Twi (Akan)', nativeName: 'Twi', region: 'Ghana' },
  { code: 'ee', name: 'Ewe', nativeName: 'Èʋegbe', region: 'Ghana / Togo' },
  { code: 'wo', name: 'Wolof', nativeName: 'Wolof', region: 'Senegal' },
  { code: 'ht', name: 'Haitian Creole', nativeName: 'Kreyòl ayisyen', region: 'Haiti / Caribbean' },

  // ─── Pacific & Indigenous Languages ───
  { code: 'haw', name: 'Hawaiian', nativeName: 'ʻŌlelo Hawaiʻi', region: 'Hawaii (USA)' },
  { code: 'sm', name: 'Samoan', nativeName: 'Gagana faʻa Sāmoa', region: 'Samoa' },
  { code: 'mi', name: 'Maori', nativeName: 'Te Reo Māori', region: 'New Zealand' },
  { code: 'to', name: 'Tongan', nativeName: 'Lea Faka-Tonga', region: 'Tonga' },
  { code: 'fj', name: 'Fijian', nativeName: 'Na Vosa Vakaviti', region: 'Fiji' },
];

export function getLanguageName(code: string): string {
  const found = SUPPORTED_LANGUAGES.find((l) => l.code.toLowerCase() === (code || '').toLowerCase());
  return found ? `${found.name} (${found.nativeName})` : code;
}

export function getLanguageByCode(code: string): SupportedLanguage | undefined {
  return SUPPORTED_LANGUAGES.find((l) => l.code.toLowerCase() === (code || '').toLowerCase());
}
